import { FilterData } from './utils';

const boardList = [
  '/3/',
  '/a/',
  '/aco/',
  '/adv/',
  '/an/',
  '/asp/',
  '/b/',
  '/bant/',
  '/biz/',
  '/c/',
  '/cgl/',
  '/ck/',
  '/cm/',
  '/co/',
  '/d/',
  '/diy/',
  '/e/',
  '/fa/',
  '/fit/',
  '/g/',
  '/gd/',
  '/gif/',
  '/h/',
  '/hc/',
  '/hm/',
  '/hr/',
  '/i/',
  '/ic/',
  '/his/',
  '/int/',
  '/jp/',
  '/k/',
  '/lit/',
  '/lgbt/',
  '/m/',
  '/mlp/',
  '/mu/',
  '/news/',
  '/n/',
  '/o/',
  '/out/',
  '/p/',
  '/po/',
  '/pol/',
  '/pw/',
  '/qst/',
  '/r/',
  '/r9k/',
  '/s4s/',
  '/s/',
  '/sci/',
  '/soc/',
  '/sp/',
  '/t/',
  '/tg/',
  '/toy/',
  '/trash/',
  '/trv/',
  '/tv/',
  '/u/',
  '/v/',
  '/vg/',
  '/vm/',
  '/vmg/',
  '/vip/',
  '/vp/',
  '/vr/',
  '/vrpg/',
  '/vst/',
  '/vt/',
  '/w/',
  '/wg/',
  '/wsg/',
  '/wsr/',
  '/x/',
  '/xs/',
  '/y/',
];

export const data: FilterData = {
  ranges: {},
  lists: { boards: { displayLabel: '4chan boards to include', value: boardList } },
  binaryProps: {
    employment: {
      displayLabel: 'Employment status',
      value: [
        'Student',
        'Part time worker',
        'Full time worker',
        'Business owner',
        'Self-Employed',
        'Unemployed but looking',
        'Neet',
      ],
    },
    religion: {
      displayLabel: 'Religion',
      value: ['Christian', 'Muslim', 'Jewish', 'Atheist', 'Hindu', 'Other'],
    },
    politic: {
      displayLabel: 'Political Beliefs',
      value: [
        'Leftist',
        'Centrist',
        'Fascist',
        'Communist',
        'Other',
        "I don't care",
        'Conservative',
      ],
    },
    online: {
      displayLabel: 'Online schedule',
      value: [
        'Most of the day',
        'In the morning',
        'Afternoon',
        'Evening',
        'A couple of times a week',
        'Rarely',
      ],
    },
  },
};
